spring.application.name=viajesgvr
# nombre interno de la aplicacion en spring boot

server.port=${SERVER_PORT:8090}
# puerto donde se ejecuta el backend
# si no se entrega SERVER_PORT, usa 8090 por defecto

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_viajesgvr}
# ruta de conexion hacia la base de datos
# localmente usa localhost, pero en docker podremos cambiarla por variable de entorno

spring.datasource.username=${DB_USERNAME:root}
# usuario con el que spring se conecta a mysql
# si no se entrega DB_USERNAME, usa root por defecto

spring.datasource.password=${DB_PASSWORD}
# toma la contraseña desde una variable de entorno llamada DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
# crea o actualiza tablas automaticamente segun las entidades

spring.jpa.show-sql=true
# muestra en consola las consultas sql que ejecuta hibernate

spring.jpa.properties.hibernate.format_sql=true
# ordena el sql en consola para que se vea mas legible

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# le indica a hibernate que trabajara con mysql

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/viajesgvr}
# indica que los tokens jwt validos seran los emitidos por el realm viajesgvr de keycloak
# debe coincidir con el issuer que viene dentro del token

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/viajesgvr/protocol/openid-connect/certs}
# indica desde donde el backend obtiene las llaves publicas para validar los tokens jwt
# en docker usaremos host.docker.internal para que el contenedor pueda llegar a keycloak